pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/vaishali1912/localRepo.git'
            }
        }

        stage('Build') {
            steps {
                dir('TestNG_selenium') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('TestNG_selenium') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('TestNG_selenium') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('TestNG_selenium') {
                    bat 'mvn package'
                }
            }
        }
         stage('Docker Build') {
            steps {
                dir('TestNG_selenium') {
                    bat 'docker build -t testng-framework .'
               }
           }
        }
        stage('Docker Run') {
            steps {
                dir('TestNG_selenium') {
                    bat 'docker run -rm testng-framework'
               }
           }
    }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
